@startuml
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho
'agencia y agente
entity "Agencia" as agencia {
    *Agencia_ID: bigint identity(1,1) <<PK>>
    --
    Agencia_Nro_Agencia: bigint
    Agencia_ID_Direccion: bigint identity(1,1) <<FK>>
    Agencia_Telefono: nvarchar(510)
    Agencia_Mail: nvarchar(510)

}
entity "Agente" as agente {
    *Agente_ID: bigint identity(1,1) <<PK>>
    --
    Agente_ID_Direccion: bigint identity(1,1) <<FK>>
    Agente_ID_Agencia: bigint identity(1,1) <<FK>>
    Agente_Legajo: bigint
    Agente_Nombre: nvarchar(510)
    Agente_Apellido: nvarchar(510)
    Agente_Dni: nvarchar(510)
    Agente_Fecha_Nac: date
    Agente_Telefono: nvarchar(510)
    Agente_Mail: nvarchar(510)
}
'cliente
entity "Cliente" as cliente {
    *Cliente_ID: bigint identity(1,1) <<PK>>
    --
    Cliente_ID_Direccion: bigint identity(1,1) <<FK>>
    Cliente_Nombre: nvarchar(510)
    Cliente_Apellido: nvarchar(510)
    Cliente_Dni: nvarchar(510)
    Cliente_Fecha_Nac: date
    Cliente_Telefono: nvarchar(510)
    Cliente_Mail: nvarchar(510)
}
'aeropuerto, vuelo y aerolinea
entity "Aerolinea" as aerolinea {
    *Aerolinea_ID: bigint identity(1,1) <<PK>>
    --
    Aerolinea_ID_Pais: bigint <<FK>>
    Aerolinea_ID_Alianza: bigint <<FK>>
    Aerolinea_Nombre: nvarchar(510)
    Aerolinea_Codigo: nvarchar(510)
}
entity "Alianza" as alianza {
    *Alianza_ID: bigint identity(1,1) <<PK>>
    --
    Alianza_Nombre: nvarchar(510)
}
entity "Aeropuerto" as aeropuerto {
    *Aeropuerto_ID: bigint identity(1,1) <<PK>>
    --
    Aeropuerto_ID_Ciudad: bigint <<FK>>
    Aeropuerto_Codigo: nvarchar(20)
    Aeropuerto_Descripcion: nvarchar(400)
}
entity "Vuelo" as vuelo {
    *Vuelo_ID: bigint identity(1,1) <<PK>>
    --
    Vuelo_ID_Aeropuerto_Salida: bigint <<FK>>
    Vuelo_ID_Aeropuerto_Llegada: bigint <<FK>>
    Vuelo_ID_Aerolinea: bigint <<FK>>
    Vuelo_Fecha_Salida: date
    Vuelo_Horario_Salida: nvarchar(100)
    Vuelo_Fecha_Llegada: date
    Vuelo_Horario_Llegada: nvarchar(100)
    Vuelo_Duracion: int
    Vuelo_Precio: decimal(18,2)
    Vuelo_Incluye_Carry: bit
    Vuelo_Incluye_Valija: bit
}
'proveedor y excursion
entity "Proveedor" as proveedor {
    *Proveedor_ID: bigint identity(1,1) <<PK>>
    --
    Proveedor_Nombre: nvarchar(510)
    Proveedor_Telefono: nvarchar(510)
    Proveedor_Mail: nvarchar(510)
}
entity "Excursion" as excursion {
    *Excursion_ID: bigint identity(1,1) <<PK>>
    --
    Excursion_ID_Proveedor: bigint <<FK>>
    Excursion_Nombre: nvarchar(510)
    Excursion_Descripcion: nvarchar(max)
    Excursion_Horario: nvarchar(100)
    Excursion_Duracion: int
    Excursion_Precio: decimal(18,2)
}
'solicitudes
entity "Solicitud" as solicitud {
    *Solicitud_ID: bigint identity(1,1) <<PK>>
    --
    Solicitud_ID_Cliente: bigint <<FK>>
    Solicitud_ID_Agente: bigint <<FK>>
    Solicitud_Nro_Solicitud: bigint
    Solicitud_Fecha_Solicitud: date
    Solicitud_Fecha_Inicio_Tentativa: date
    Solicitud_Fecha_Fin_Tentativa: date
    Solicitud_Cantidad_Pasajeros: int
    Solicitud_Observaciones: nvarchar(max)
    Solicitud_Presupuesto_Estimado: decimal(18,2)
}
entity "Solicitud_X_Ciudad" as solicitud_ciudad {
    *Solicitud_X_Ciudad_ID: bigint identity(1,1) <<PK>>
    --
    Solicitud_X_Ciudad_ID_Solicitud: bigint <<FK>>
    Solicitud_X_Ciudad_ID_Ciudad: bigint <<FK>>
    Solicitud_X_Ciudad_Cantidad_Dias_Aprox: int
    Solicitud_X_Ciudad_Observaciones: nvarchar(-1)
}
'propuestas
entity "Propuesta" as propuesta {
    *Propuesta_ID: bigint identity(1,1) <<PK>>
    --
    Propuesta_ID_Solicitud: bigint<<FK>>
    Propuesta_ID_Agente: bigint<<FK>>
    Propuesta_ID_Estado: bigint <<FK>>
    Propuesta_Nro_Propuesta: bigint
    Propuesta_Fecha_Emision: date
    Propuesta_Fecha_Vigencia_Hasta: date
    Propuesta_Fecha_Desde: date
    Propuesta_Fecha_Hasta: date
    Propuesta_Subtotal: decimal(18,2)
    Propuesta_Descuento: decimal(18,2)
    Propuesta_Importe_Total: decimal(18,2)
}
entity "Estado_Propuesta" as estado_propuesta {
    *Estado_Propuesta_ID_: bigint identity(1,1) <<PK>>
    --
    Estado_Propuesta_Tipo: nvarchar(510)
}
entity "Propuesta_X_Vuelo" as propuesta_vuelo {
    *Propuesta_X_Vuelo_ID: bigint identity(1,1) <<PK>>
    --
    Propuesta_X_Vuelo_ID_Propuesta: bigint <<FK>>
    Propuesta_X_Vuelo_ID_Vuelo: bigint<<FK>>
    Propuesta_X_Vuelo_Cantidad_Pasajes: int
    Propuesta_X_Vuelo_Precio_Unitario: decimal(18,2)
    Propuesta_X_Vuelo_Subtotal: decimal(18,2)
}
entity "Propuesta_X_Habitacion" as propuesta_habitacion {
    *Propuesta_X_Habitacion_ID: bigint identity(1,1) <<PK>>
    --
    Propuesta_X_Habitacion_ID_Propuesta: bigint <<FK>>
    Propuesta_X_Habitacion_ID_Habitacion: bigint <<FK>>
    Propuesta_X_Habitacion_Fecha_Desde: date
    Propuesta_X_Habitacion_Fecha_Hasta: date
    Propuesta_X_Habitacion_Cantidad_Habitaciones: int
    Propuesta_X_Habitacion_Precio_Unitario: decimal(18,2)
    Propuesta_X_Habitacion_Subtotal: decimal(18,2)
}
'hospedaje y habitacion
entity "Hospedaje" as hospedaje {
    *Hospedaje_ID: bigint identity(1,1) <<PK>>
    --
    Hospedaje_ID_Ciudad: bigint <<FK>>
    Hospedaje_ID_Direccion: bigint<<FK>>
    Hospedaje_Nombre: nvarchar(510)
    Hospedaje_Incluye_Desayuno: bit
    Hospedaje_Check_In: nvarchar(100)
    Hospedaje_Check_Out: nvarchar(100)
}
entity "Habitacion" as habitacion {
    *Habitacion_ID: bigint identity(1,1) <<PK>>
    --
    Habitacion_ID_Hospedaje: bigint <<FK>>
    Habitacion_Nombre: nvarchar(510)
    Habitacion_Descripcion: nvarchar(max)
    Habitacion_Precio_Noche: decimal(18,2)
}
'reserva
entity "Reserva" as reserva {
    *Reserva_ID: bigint identity(1,1) <<PK>>
    --
    Reserva_Cod_Reserva: nvarchar(510)
    Reserva_Fecha_Reserva: timestamp
}
' ventas
entity "Venta" as venta {
    *Venta_ID: bigint identity(1,1) <<PK>>
    --
    Venta_Nro_Venta: bigint
    Venta_Fecha_Venta: date
    Venta_ID_Cliente: bigint <<FK>>
    Venta_ID_Agente: bigint <<FK>>
    Venta_ID_Agencia: bigint <<FK>>
    Venta_ID_Medio_Pago: bigint <<FK>>
    Venta_ID_Canal_Venta: bigint <<FK>>
    Venta_Subtotal: decimal(18,2)
    Venta_Descuento: decimal(18,2)
    Venta_Importe_Total: decimal(18,2)
}
entity "Canal_Venta" as canal_venta {
    *Canal_Venta_ID: bigint identity(1,1) <<PK>>
    --
    Canal_Venta_Nombre: nvarchar(510)
}
entity "Medio_Pago" as medio_pago {
    *Medio_Pago_ID: bigint identity(1,1) <<PK>>
    --
    Medio_Pago_Nombre: nvarchar(510)
}
entity "Venta_X_Vuelo" as venta_vuelo {
    *Venta_X_Vuelo_ID: bigint identity(1,1) <<PK>>
    --
    Venta_X_Vuelo_ID_Venta: bigint <<FK>>
    Venta_X_Vuelo_ID_Vuelo: bigint <<FK>>
    Venta_X_Vuelo_ID_Reserva: bigint <<FK>>
    Venta_X_Vuelo_Vuelo_Cantidad_Pasajes: int
    Venta_X_Vuelo_Vuelo_Precio_Unitario: decimal(18,2)
    Venta_X_Vuelo_Subtotal: decimal(18,2)
}
entity "Venta_X_Habitacion" as venta_habitacion {
    *Venta_X_Habitacion_ID: bigint identity(1,1) <<PK>>
    --
    Venta_X_Habitacion_ID_Venta: bigint <<FK>>
    Venta_X_Habitacion_ID_Habitacion: bigint <<FK>>
    Venta_X_Habitacion_ID_Reserva: bigint<<FK>>
    Venta_X_Habitacion_Fecha_Desde: date
    Venta_X_Habitacion_Fecha_Hasta: date
    Venta_X_Habitacion_Cantidad_Habitaciones: int
    Venta_X_Habitacion_Precio_Unitario: decimal(18,2)
    Venta_X_Habitacion_Subtotal: decimal(18,2)
}
entity "Venta_X_Excursion" as venta_excursion {
    *Venta_X_Excursion_ID: bigint identity(1,1) <<PK>>
    --
    Venta_X_Excursion_ID_Venta: bigint <<FK>>
    Venta_X_Excursion_ID_Excursion: bigint <<FK>>
    Venta_X_Excursion_ID_Reserva: bigint<<FK>>
    Venta_X_Excursion_Excursion_Fecha_Reserva: date
    Venta_X_Excursion_Excursion_Cantidad: int
    Venta_X_Excursion_Excursion_Precio_Unitario: decimal(18,2)
    Venta_X_Excursion_Subtotal: decimal(18,2)
}
entity "Venta_X_Propuesta" as venta_propuesta {
    *Venta_X_Propuesta_ID: bigint identity(1,1) <<PK>>
    --
    Venta_X_Propuesta_ID_Venta: bigint<<FK>>,
    Venta_X_Propuesta_ID_Propuesta: bigint<<FK>>,
}
' encuesta
entity "Encuesta" as encuesta {
    *Encuesta_ID: bigint identity(1,1) <<PK>>
    --
    Encuesta_ID_Cliente: bigint <<FK>>
    Encuesta_ID_Agente: bigint <<FK>>
    Encuesta_Codigo_Encuesta: bigint
    Encuesta_Fecha_Encuesta: date
    Encuesta_Comentarios: nvarchar(max)
}
entity "Encuesta_Venta" as encuesta_venta {
    *Encuesta_Venta_ID: bigint identity(1,1) <<PK>>
    --
    Encuesta_Venta_ID_Encuesta: bigint <<FK>>
    Encuesta_Venta_ID_Venta: bigint <<FK>>
}
entity "Encuesta_Propuesta" as encuesta_propuesta {
    *Encuesta_Propuesta_ID: bigint identity(1,1) <<PK>>
    --
    Encuesta_Propuesta_ID_Encuesta: bigint <<FK>>
    Encuesta_Propuesta_ID_Propuesta: bigint <<FK>>
}
entity "Encuesta_X_Aspecto" as encuesta_aspecto {
    *Encuesta_X_Aspecto_ID: bigint identity(1,1) <<PK>>
    --
    Encuesta_X_Aspecto_ID_Encuesta: bigint <<FK>>
    Encuesta_X_Aspecto_ID_Aspecto: bigint <<FK>>
    Encuesta_X_Aspecto_Puntaje: int
}
entity "Aspecto" as aspecto {
    *Aspecto_ID: bigint identity(1,1) <<PK>>
    --
    Aspecto_Tipo: nvarchar(510)
}
' locaciones
entity "Pais" as pais {
    *Pais_ID: bigint identity(1,1) <<PK>>
    --
    Pais_Nombre: nvarchar(510)
}
entity "Ciudad" as ciudad {
    *Ciudad_ID: bigint identity(1,1) <<PK>>
    --
    Ciudad_Nombre: nvarchar(510)
    Ciudad_ID_Pais: bigint <<FK>>
}
entity "Provincia" as provincia {
    *Provincia_ID: bigint identity(1,1) <<PK>>
    --
    Provincia_Nombre: nvarchar(510)
}
entity "Localidad" as localidad {
    *Localidad_ID: bigint identity(1,1) <<PK>>
    --
    Localidad_Nombre: nvarchar(510)
    Localidad_ID_Provincia: bigint <<FK>>
}
entity "Direccion" as direccion {
    *Direccion_ID: bigint identity(1,1) <<PK>>
    --
    Direccion: nvarchar(510)
    Direccion_ID_Localidad: bigint <<FK>>
}

aerolinea }|--|| pais
aerolinea }|-right-o| alianza
aeropuerto }|--|| ciudad
agente }|--|| direccion
agente }|--|| agencia
agencia ||--|| direccion

ciudad }|--|| pais
cliente }|--|| direccion

direccion }|--|| localidad

encuesta_aspecto }|-up-|| aspecto
encuesta_aspecto }|--|| encuesta
encuesta_propuesta }o-up-|| encuesta
encuesta_propuesta }o--|| propuesta
encuesta_venta }o-up-|| encuesta
encuesta_venta }o--|| venta
estado_propuesta }|--|| propuesta
excursion }|--|| proveedor

habitacion }|-left-|| hospedaje
hospedaje }|--|| ciudad
hospedaje }|--|| direccion

localidad }|--|| provincia

solicitud }|-left-|| cliente
solicitud }|--o| agente
solicitud_ciudad }|-left-|| solicitud
solicitud_ciudad }|--|| ciudad
 
propuesta }o--|| solicitud
propuesta }|--|| agente
propuesta_habitacion }|--|| propuesta
propuesta_habitacion }|--|| habitacion
propuesta_vuelo }|--|| propuesta
propuesta_vuelo }|-up-|| vuelo

venta }|--|| cliente
venta }|--|| agente
venta }|--|| agencia
venta }|--|| medio_pago
venta }|--|| canal_venta

venta_excursion }|--|| reserva
venta_habitacion }|--|| reserva
venta_vuelo }|--|| reserva

venta_propuesta }|--|| venta
venta_propuesta }|--|| propuesta
venta_excursion }|--|| venta
venta_excursion }|--|| excursion
venta_habitacion }|-up-|| venta
venta_habitacion }|--|| habitacion
venta_vuelo }|--|| venta
venta_vuelo }|--|| vuelo
vuelo }|--|| aeropuerto
vuelo }|--|| aeropuerto
vuelo }|--|| aerolinea

@enduml