@startuml
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho
'agencia y agente
entity "Agencia" as agencia {
    *id: bigint identity(1,1) <<PK>>
    --
    ID_Direccion: bigint identity(1,1) <<FK>>
    Telefono: nvarchar(510)
    Mail: nvarchar(510)

}
entity "Agente" as agente {
  *id : bigint identity(1,1) <<PK>>
  --
    ID_Direccion: bigint identity(1,1) <<FK>>
    Legajo: bigint
    Nombre: nvarchar(510)
    Apellido: nvarchar(510)
    Dni: nvarchar(510)
    Fecha_Nac: date
    Telefono: nvarchar(510)
    Mail: nvarchar(510)
}
'cliente
entity "Cliente" as cliente {
    *id: bigint identity(1,1) <<PK>>
    --
    ID_Direccion: bigint identity(1,1) <<FK>>
    Nombre: nvarchar(510)
    Apellido: nvarchar(510)
    Dni: nvarchar(510)
    Fecha_Nac: date
    Telefono: nvarchar(510)
    Mail: nvarchar(510)
}
'aeropuerto, vuelo y aerolinea
entity "Aerolinea" as aerolinea {
    *id: bigint identity(1,1) <<PK>>
    --
    ID_Pais: bigint <<FK>>
    Nombre: nvarchar(510)
    Codigo: nvarchar(510)
    Alianza: nvarchar(510)
}
entity "Aeropuerto" as aeropuerto {
    *id: bigint identity(1,1) <<PK>>
    --
    ID_Ciudad: bigint <<FK>>
    Codigo: nvarchar(20)
    Descripcion: nvarchar(400)
}
entity "Vuelo" as vuelo {
    *id: bigint identity(1,1) <<PK>>
    --
    Fecha_Salida: date
    Horario_Salida: nvarchar(100)
    Fecha_Llegada: date
    Horario_Llegada: nvarchar(100)
    Duracion: int
    Precio: decimal(18,2)
    Incluye_Carry: bit
    Incluye_Valija: bit
}
'proveedor y excursion
entity "Proveedor" as proveedor {
    *id: bigint identity(1,1) <<PK>>
    --
    Nombre: nvarchar(510)
    Telefono: nvarchar(510)
    Mail: nvarchar(510)
}
entity "Excursion" as excursion {
    *id: bigint identity(1,1) <<PK>>
    --
    ID_Proveedor: bigint <<FK>>
    Nombre: nvarchar(510)
    Descripcion: nvarchar(-1)
    Horario: nvarchar(100)
    Duracion: int
}
'solicitudes
entity "Solicitud" as solicitud {
    *id: bigint identity(1,1) <<PK>>
    --
    ID_Cliente: bigint <<FK>>
    ID_Agente: bigint <<FK>>
    Nro_Solicitud: bigint
    Fecha_Solicitud: date
    Fecha_Inicio_Tentativa: date
    Fecha_Fin_Tentativa: date
    Cant_Pasajeros: int
    Observaciones: nvarchar(-1)
    Presupuesto_Estimado: decimal(18,2)
}
entity "Solicitud_X_Ciudad" as solicitud_ciudad {
    *id: bigint identity(1,1) <<PK>>
    --
    ID_Solicitud: bigint <<FK>>
    ID_Ciudad: bigint <<FK>>
    Cant_Dias_Aprox: int
    Observaciones: nvarchar(-1)
}
'propuestas
entity "Propuesta" as propuesta {
    *id: bigint identity(1,1) <<PK>>
    --
    ID_Solicitud: bigint<<FK>>
    ID_Agente: bigint<<FK>>
    ID_Estado: bigint <<FK>>
    Nro_Propuesta: bigint
    Fecha_Emision: date
    Fecha_Vigencia_Hasta: date
    Fecha_Desde: date
    Fecha_Hasta: date
    Descuento: decimal(18,2)
}
entity "Estado_Propuesta" as estado_propuesta {
    *id: bigint identity(1,1) <<PK>>
    --
    Estado: nvarchar(510)
}
entity "Propuesta_X_Vuelo" as propuesta_vuelo {
    *id: bigint identity(1,1) <<PK>>
    --
    ID_Propuesta: bigint <<FK>>
    ID_Vuelo: bigint<<FK>>
    Cant_Pasajes: int
    Precio: decimal(18,2)
}
entity "Propuesta_X_Hospedaje" as propuesta_hospedaje {
    *id: bigint identity(1,1) <<PK>>
    --
    ID_Propuesta: bigint <<FK>>
    ID_Hospedaje: bigint <<FK>>
    ID_Habitacion: bigint <<FK>>
    Fecha_Desde: date
    Fecha_Hasta: date
    Cant_Habitaciones: int
    Precio: decimal(18,2)
}
'hospedaje y habitacion
entity "Hospedaje" as hospedaje {
    *id: bigint identity(1,1) <<PK>>
    --
    ID_Ciudad: bigint <<FK>>
    ID_Direccion: bigint<<FK>>
    Nombre: nvarchar(510)
    Incluye_Desayuno: bit
    Check_In: nvarchar(100)
    Check_Out: nvarchar(100)
}
entity "Habitacion" as habitacion {
    *id: bigint identity(1,1) <<PK>>
    --
    ID_Hospedaje: bigint <<FK>>
    Nombre: nvarchar(510)
    Descripcion: nvarchar(-1)
    Precio_Noche: decimal(18,2)
}
'reserva
entity "Reserva" as reserva {
    *id: bigint identity(1,1) <<PK>>
    --
    Cod_Reserva: nvarchar(510)
    Fecha_Reserva: timestamp
}
' ventas
entity "Venta" as venta {
    *id: bigint identity(1,1) <<PK>>
    --
    Nro_Venta: bigint
    Fecha_Venta: date
    Canal_Venta: nvarchar(510)
    Medio_Pago: nvarchar(510)
    Descuento: decimal(18,2)
}
entity "Venta_X_Vuelo" as venta_vuelo {
    *id: bigint identity(1,1)
    --
    ID_Venta: bigint <<FK>>
    ID_Vuelo: bigint <<FK>>
    ID_Reserva: bigint <<FK>>
    Vuelo_Cantidad_Pasajes: int
    Vuelo_Precio_Unitario: decimal(18,2)
}
entity "Venta_X_Hospedaje" as venta_hospedaje {
    *id: bigint identity(1,1)
    --
    ID_Venta: bigint <<FK>>
    ID_Hospedaje: bigint <<FK>>
    ID_Habitacion: bigint <<FK>>
    ID_Reserva: bigint<<FK>>
    Hospedaje_Fecha_Desde: date
    Hospedaje_Fecha_Hasta: date
    Hospedaje_Cantidad: int
    Hospedaje_Precio_Unitario: decimal(18,2)
}
entity "Venta_X_Excursion" as venta_excursion {
    *id: bigint identity(1,1) <<PK>>
    --
    ID_Venta: bigint <<FK>>
    ID_Excursion: bigint <<FK>>
    ID_Reserva: bigint<<FK>>
    Excursion_Fecha_Reserva: date
    Excursion_Cant: int
    Excursion_Precio_Unitario: decimal(18,2)
}
' encuesta
entity "Encuesta" as encuesta {
    *id: bigint identity(1,1) <<PK>>
    --
    ID_Cliente: bigint <<FK>>
    ID_Agente: bigint <<FK>>
    ID_Venta: bigint <<FK>>
    ID_Propuesta: bigint <<FK>>
    Codigo_Encuesta: bigint
    Fecha_Encuesta: date
    Comentarios: nvarchar(-1)
}
entity "Encuesta_Venta" as encuesta_venta {
    *id: bigint identity(1,1) <<PK>>
    --
    ID_Encuesta: bigint <<FK>>
    ID_Propuesta: bigint <<FK>>
}
entity "Encuesta_Propuesta" as encuesta_propuesta {
    *id: bigint identity(1,1) <<PK>>
    --
    ID_Encuesta: bigint <<FK>>
    ID_Propuesta: bigint <<FK>>
}
entity "Encuesta_X_Aspecto" as encuesta_aspecto {
    *id: bigint identity(1,1) <<PK>>
    --
    ID_Encuesta: bigint <<FK>>
    ID_Aspecto: bigint <<FK>>
    Puntaje: int
}
entity "Aspecto" as aspecto {
    *id: bigint identity(1,1) <<PK>>
    --
    Aspecto: nvarchar(510)
}
' locaciones
entity "Pais" as pais {
    *id: bigint identity(1,1) <<PK>>
    --
    Nombre: nvarchar(510)
}
entity "Ciudad" as ciudad {
    *id: bigint identity(1,1) <<PK>>
    --
    Nombre: nvarchar(510)
}
entity "Provincia" as provincia {
    *id: bigint identity(1,1) <<PK>>
    --
    Nombre: nvarchar(510)
}
entity "Localidad" as localidad {
    *id: bigint identity(1,1) <<PK>>
    --
    Nombre: nvarchar(510)
    ID_Provincia: bigint <<FK>>
}
entity "Direccion" as direccion {
    *id: bigint identity(1,1) <<PK>>
    --
    Direccion: nvarchar(510)
    ID_Localidad: bigint <<FK>>
}

aerolinea }|--|| pais
aeropuerto }|--|| ciudad
agente }|--|| direccion
agente }|--|| agencia
agencia ||--|| direccion

ciudad }|--|| pais
cliente }|--|| direccion

direccion }|--|| localidad

encuesta_aspecto }|--|| aspecto
encuesta_aspecto }|--|| encuesta
encuesta_propuesta }o--|| encuesta
encuesta_propuesta }o--|| propuesta
encuesta_venta }o--|| encuesta
encuesta_venta }o--|| venta
estado_propuesta }|--|| propuesta
excursion }|--|| proveedor

habitacion }|--|| hospedaje
hospedaje ||--|| ciudad
hospedaje ||--|| direccion

localidad }|--|| provincia

solicitud }|--o| cliente
solicitud }|--o| agente
solicitud_ciudad }|--|| solicitud
solicitud_ciudad }|--|| ciudad

propuesta |o--o| venta
propuesta }|--|| solicitud
propuesta }|--o| agente
propuesta_hospedaje }|--|| propuesta
propuesta_hospedaje }|--|| hospedaje
propuesta_hospedaje }|--|| habitacion
propuesta_vuelo }|--|| propuesta
propuesta_vuelo }|--|| vuelo

venta_excursion }|--|| reserva
venta_hospedaje }|--|| reserva
venta_vuelo }|--|| reserva

venta_excursion }|--|| venta
venta_excursion }|--|| excursion
venta_hospedaje }|--|| venta
venta_hospedaje }|--|| hospedaje
venta_hospedaje }|--|| habitacion
venta_vuelo }|--|| venta
venta_vuelo }|--|| vuelo

@enduml