USE [GD1C2026]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [gd_esquema].[Maestra](
	[Agencia_Nro_Agencia] [bigint] NULL,
	[Agencia_Direccion] [nvarchar](255) NULL,
	[Agencia_Telefono] [nvarchar](255) NULL,
	[Agencia_Mail] [nvarchar](255) NULL,
	[Agencia_Localidad] [nvarchar](255) NULL,
	[Agencia_Provincia] [nvarchar](255) NULL,
	[Agente_Legajo] [bigint] NULL,
	[Agente_Nombre] [nvarchar](255) NULL,
	[Agente_Apellido] [nvarchar](255) NULL,
	[Agente_Dni] [nvarchar](255) NULL,
	[Agente_Fecha_Nac] [date] NULL,
	[Agente_Telefono] [nvarchar](255) NULL,
	[Agente_Mail] [nvarchar](255) NULL,
	[Agente_Direccion] [nvarchar](255) NULL,
	[Agente_Localidad] [nvarchar](255) NULL,
	[Agente_Provincia] [nvarchar](255) NULL,
	[Cliente_Nombre] [nvarchar](255) NULL,
	[Cliente_Apellido] [nvarchar](255) NULL,
	[Cliente_Dni] [nvarchar](255) NULL,
	[Cliente_Tel] [nvarchar](255) NULL,
	[Cliente_Mail] [nvarchar](255) NULL,
	[Cliente_Direccion] [nvarchar](255) NULL,
	[Cliente_Fecha_Nac] [date] NULL,
	[Cliente_Localidad] [nvarchar](255) NULL,
	[Cliente_Provincia] [nvarchar](255) NULL,
	[Solicitud_Nro_Solicitud] [bigint] NULL,
	[Solicitud_Fecha_Solicitud] [date] NULL,
	[Solicitud_Fecha_Inicio_Tentativa] [date] NULL,
	[Solicitud_Fecha_Fin_Tentativa] [date] NULL,
	[Solicitud_Cant_Pax] [int] NULL,
	[Solicitud_Observaciones] [nvarchar](max) NULL,
	[Solicitud_Presupuesto_Estimado] [decimal](18, 2) NULL,
	[Detalle_Solicitud_Ciudad] [nvarchar](255) NULL,
	[Detalle_Solicitud_Cant_Dias_Aprox] [int] NULL,
	[Detalle_Solicitud_Observaciones] [nvarchar](max) NULL,
	[Propuesta_Nro_Propuesta] [bigint] NULL,
	[Propuesta_Fecha_Emision] [date] NULL,
	[Propuesta_Vigencia_Hasta] [date] NULL,
	[Propuesta_Fecha_Desde] [date] NULL,
	[Propuesta_Fecha_Hasta] [date] NULL,
	[Propuesta_Subtotal] [decimal](18, 2) NULL,
	[Propuesta_Descuento] [decimal](18, 2) NULL,
	[Propuesta_Importe_Total] [decimal](18, 2) NULL,
	[Propuesta_Estado] [nvarchar](255) NULL,
	[Detalle_Propuesta_Vuelo_Cant_Pasajes] [int] NULL,
	[Detalle_Propuesta_Vuelo_Precio] [decimal](18, 2) NULL,
	[Detalle_Propuesta_Vuelo_Subtotal] [decimal](18, 2) NULL,
	[Detalle_Propuesta_Hospedaje_Fecha_Desde] [date] NULL,
	[Detalle_Propuesta_Hospedaje_Fecha_Hasta] [date] NULL,
	[Detalle_Propuesta_Hospedaje_Cant] [int] NULL,
	[Detalle_Propuesta_Hospedaje_Precio] [decimal](18, 2) NULL,
	[Detalle_Propuesta_Hospedaje_Subtotal] [decimal](18, 2) NULL,
	[Proveedor_Nombre] [nvarchar](255) NULL,
	[Proveedor_Mail] [nvarchar](255) NULL,
	[Proveedor_Telefono] [nvarchar](255) NULL,
	[Aeropuerto_Salida_Codigo] [nvarchar](10) NULL,
	[Aeropuerto_Salida_Descripcion] [nvarchar](200) NULL,
	[Aeropuerto_Salida_Ciudad] [nvarchar](255) NULL,
	[Aeropuerto_Salida_Pais] [nvarchar](255) NULL,
	[Aeropuerto_Llegada_Codigo] [nvarchar](10) NULL,
	[Aeropuerto_Llegada_Descripcion] [nvarchar](200) NULL,
	[Aeropuerto_Llegada_Ciudad] [nvarchar](255) NULL,
	[Aeropuerto_Llegada_Pais] [nvarchar](255) NULL,
	[Aerolinea_Nombre] [nvarchar](255) NULL,
	[Aerolinea_Codigo] [nvarchar](255) NULL,
	[Aerolinea_Pais] [nvarchar](255) NULL,
	[Aerolinea_Alianza] [nvarchar](255) NULL,
	[Vuelo_Fecha_Salida] [date] NULL,
	[Vuelo_Horario_Salida] [nvarchar](50) NULL,
	[Vuelo_Fecha_Llegada] [date] NULL,
	[Vuelo_Horario_Llegada] [nvarchar](50) NULL,
	[Vuelo_Duracion] [int] NULL,
	[Vuelo_Precio] [decimal](18, 2) NULL,
	[Vuelo_Incluye_Carry] [bit] NULL,
	[Vuelo_Incluye_Valija] [bit] NULL,
	[Hospedaje_Ciudad] [nvarchar](255) NULL,
	[Hospedaje_Pais] [nvarchar](255) NULL,
	[Hospedaje_Nombre] [nvarchar](255) NULL,
	[Hospedaje_Direccion] [nvarchar](255) NULL,
	[Hospedaje_Incluye_Desayuno] [bit] NULL,
	[Hospedaje_Check_In] [nvarchar](50) NULL,
	[Hospedaje_Check_Out] [nvarchar](50) NULL,
	[Habitacion_Nombre] [nvarchar](255) NULL,
	[Habitacion_Descripcion] [nvarchar](max) NULL,
	[Habitacion_Precio_Noche] [decimal](18, 2) NULL,
	[Excursion_Nombre] [nvarchar](255) NULL,
	[Excursion_Descripcion] [nvarchar](max) NULL,
	[Excursion_Horario] [nvarchar](50) NULL,
	[Excursion_Duracion] [int] NULL,
	[Excursion_Precio] [decimal](18, 2) NULL,
	[Venta_Nro_Venta] [bigint] NULL,
	[Venta_Fecha_Venta] [date] NULL,
	[Venta_Canal_Venta] [nvarchar](255) NULL,
	[Venta_Medio_Pago] [nvarchar](255) NULL,
	[Venta_Subtotal] [decimal](18, 2) NULL,
	[Venta_Descuento] [decimal](18, 2) NULL,
	[Venta_Importe_Total] [decimal](18, 2) NULL,
	[Detalle_Venta_Vuelo_Cantidad_Pasajes] [int] NULL,
	[Detalle_Venta_Vuelo_Precio_Unitario] [decimal](18, 2) NULL,
	[Detalle_Venta_Vuelo_Subtotal] [decimal](18, 2) NULL,
	[Detalle_Venta_Vuelo_Cod_Reserva] [nvarchar](255) NULL,
	[Detalle_Venta_Hospedaje_Fecha_Desde] [date] NULL,
	[Detalle_Venta_Hospedaje_Fecha_Hasta] [date] NULL,
	[Detalle_Venta_Hospedaje_Cantidad] [int] NULL,
	[Detalle_Venta_Hospedaje_Precio_Unitario] [decimal](18, 2) NULL,
	[Detalle_Venta_Hospedaje_Subtotal] [decimal](18, 2) NULL,
	[Detalle_Venta_Hospedaje_Cod_Reserva] [nvarchar](255) NULL,
	[Detalle_Venta_Excursion_Fecha_Reserva] [date] NULL,
	[Detalle_Venta_Excursion_Cant] [int] NULL,
	[Detalle_Venta_Excursion_Precio_Unitario] [decimal](18, 2) NULL,
	[Detalle_Venta_Excursion_Subtotal] [decimal](18, 2) NULL,
	[Detalle_Venta_Excursion_Cod_Reserva] [nvarchar](255) NULL,
	[Aspecto_Aspecto] [nvarchar](255) NULL,
	[Encuesta_Codigo_Encuesta] [bigint] NULL,
	[Encuesta_Fecha_Encuesta] [date] NULL,
	[Encuesta_Comentarios] [nvarchar](max) NULL,
	[Detalle_Encuesta_Puntaje] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


